"""Call functions with arguments generated by a local large language model"""
from .generator import Generator
from .prompter import CompletionModelPrompter, InstructModelPrompter, TextPrompter

__all__ = [
    "Generator",
    "CompletionModelPrompter",
    "InstructModelPrompter",
    "TextPrompter",
]
